### PR TITLE
fix requirements range error for travis test

### PR DESCRIPTION
**Pull request by ccnifo**
Set correct parsable ranges on module requirements to pass Travis tests

### CODE REVIEW

**Comment by ccnifo** [comment]
@kreczko : I saw that stdlib 5.2.0 is available, maybe we can test it to enlarge the supported version range? Release notes say:

> This is a major release which removes support for the Scientific 5 and Debian 7 OS, as well as a removal of the Stdlib::(Ipv4|IPv6|Ip_address) data types in favour of Stdlib::IP::*.

**Comment by kreczko** [comment]
sure, let's try it

**Comment by ccnifo** [comment]
I ran a pass with stdlib 5.2.0 on my CentOS7 cluster, no warning whatsoever on worker, master, or scheduler. Of course, one can have a different experience on a different cluster.

**Comment by ccnifo** [comment]
@kreczko and I've seen no mention of stdlib::ip in the module, so I guess we're OK? Would you prefer to merge as is or to include 5.x?

**Comment by ccnifo** [comment]
@kreczko  : re-reading the release notes of stdlib 5.0.0 makes me thing it should run fine.
However, 1 or 2 module users testing it would be great!

**Pull request merged**
