### PR TITLE
2016 spring clean

### PR DESCRIPTION
**Pull request by kreczko**
- fixing issue #42 (ea44a55)
 - fixing authentications problems (0ddc632, 18c9253, 1eeea45, 1df9a63, ca5595e, f47a368)
 - made PID name spaces and account mapping optional (now `disabled` by default as requested by ATLAS)
 - added options to adjuts wall-time & cpu-time limits

### CODE REVIEW

**Comment by kreczko** [comment]
@kashif74 @rwf14f @fschaer : I will leave this open until Tuesday, feel free to comment :)

**Comment by fschaer** [comment]
Mmm... lots of incompatible changes, no ?
PID namespaces used to ba an atlas pilots killer feature (meaning : all atlas jobs commiting suicide)... would that be fixed ?

**Comment by kreczko** [comment]
Not sure I understand the comment.
PID namespaces used to be enabled by default before this patch and still will be after it. The only change is that you can turn them off now.

Most of the changes should be compatible with previous settings, but maybe I am just looked at the code for too long ;).

**Comment by fschaer** [comment]
Hi Luke,

This is what I have in my own condor template : 
# email from andrew :
# Are you able to get log files for these jobs, or are the Panda links empty? Assuming there are no log files, if you have PID namespaces enabled you could try disabling them 
# the ATLAS pilot.py gets confused when it tries to detect orphaned processes and ends up killing itself, resulting in not being able to get the usual log files. 
# (We're trying to get ATLAS to fix this BTW).
#USE_PID_NAMESPACES = true
USE_PID_NAMESPACES = false

And indeed, disabling that made the atlas jobs work. Thei previously failed. But indeed,  your changes do not change the previous behaviour.

Also, I'm a bit worried about :

(default) AUTHENTICATION_METHODS which contain ANONYMOUS
SCHEDD.ALLOW_WRITE which now contains the WNS (why ?)
The machine_list_prefix (and the list itself), which is clearly different by default from what we had before, hence, I presume this might break something during a module upgrade (or not, I'm too new to htcondor to understand correctly almost any feature) ... ?

Regards

**Comment by kreczko** [comment]
Thanks for the feedback

We can definitely change the default behaviour to `USE_PID_NAMESPACES = false`.

> Also, I'm a bit worried about :
> (default) AUTHENTICATION_METHODS which contain ANONYMOUS

This is taken from https://www.gridpp.ac.uk/wiki/Example_Build_of_an_ARC/Condor_Cluster. Both Lancaster and RAL T1 seem to have this bit in (in fact CLAIMTOBE in Lancaster and ANONYMOUS at the T1). At least in the version they had at the time. I remember it fixing something. I can try changing it on our cluster to see what happens
> SCHEDD.ALLOW_WRITE which now contains the WNS (why ?)

Apologies, that is indeed a change that should have stayed local and in fact is no longer needed (we used to allow local users to login into our WNs and submit from there
 

> The machine_list_prefix (and the list itself), which is clearly different by default from what we had before, hence, I presume this might break something during a module upgrade (or not, I'm too new to htcondor to understand correctly almost any feature) ... 

This corresponds to the previous default (condor_user, `condor` by default) with added `condor_pool` entries (what the daemons use to authenticate), e.g.:
```
CMS = condor@$(UID_DOMAIN)/htc00.dice.priv, condor@$(UID_DOMAIN)/htc01.dice.priv
```
changes to 
```
CMS = condor_pool@$(UID_DOMAIN)/htc00.dice.priv, condor_pool@$(UID_DOMAIN)/htc01.dice.priv, \
condor@$(UID_DOMAIN)/htc00.dice.priv, condor@$(UID_DOMAIN)/htc01.dice.priv
```
Therefore it is more permissive (adding daemon-daemon communication) than the previous default and should not break anything.

Thanks a lot for the feedback I will change the PR to incorporate the suggested changes.

**Comment by kreczko** [comment]
OK, the newest set has:
 - `ANONYMOUS` removed from  `AUTHENTICATION_METHODS`
 - PID name spaces are now `false` by default
 - removed worker nodes from `SCHEDD.ALLOW_WRITE`

Looking forward to more feedback. 
If possible I would like to get this module (and `arc_ce`) a bit more in shape so I can advertise it at the next HTCondor workshop (end of Feb).

**Comment by kreczko** [comment]
One thing I forgot about before is now in 0ddc632:
"Introduction of new security default added two condor users, submit-side@matchsession and execute-side@matchsession, that needed DAEMON level access on worker nodes. This default is fixed in condor 8.5.1 but 8.5.1 is a development release."

**Comment by kreczko** [comment]
I have now updated the description.
Any more feedback regarding this issue (@fschaer, @kashif74, @rwf14f)?
If I hear nothing by tomorrow 12:00 GMT, I will merge the PR.

In preparation to the merge I have created a new release:
https://github.com/HEP-Puppet/htcondor/releases/tag/v1.3.0
and I will update the README after the merge (last stable release -> 1.3.0).
Master will be then heading towards 2.0 with potentially breaking changes or changed defaults (as in this PR). After merge I will create a draft release to track the changes since 1.3.0.

**Comment by kreczko** [comment]
I realised that it would be better for everyone if I do not merge the changes into master.
I will merge them into the `dev` branch instead and make a release candidate for testing once all features are complete. This way I will not break anything and therefore should be able to merge more quickly.

**Pull request closed without merging**
