### PR TITLE
Kerberos auth support in security config

### PR DESCRIPTION
**Pull request by ccnifo**
This PR aims at integrating config parameters for kerberos auth.
It splits into:

-  replacing  the ineffective (missing) krb_map_file_source with a template. For now, enabling krb_map_file just produces an error.
- adding to security config the kerberos related params.

Some keywords (I think of "Optional") should break Puppet 3 compatibility; it's not an officially supported Puppet version now, but if for some reason compatbility is required, I should be able to change it. But I have no Puppet 3 test platform to ensure compatibility.

This PR should probably come with some documentation, could you please point me out where I should put it?

Thanks,

### CODE REVIEW

**Comment by ccnifo** [comment]
No activity on this repo since 2+ months, is there a problem?

**Comment by kreczko** [comment]
Apologies, this indeed fell under the radar.

The travis-ci checks are still failing, but only for Puppet 3:
```bash
Could not parse for environment *root*: Syntax error at 'Optional'; expected ')' at /home/travis/build/HEP-Puppet/htcondor/manifests/config/security.pp:2
```
I assume 'Optional' is not in Puppet 3's vocabulary.

While I am all in favour to switch to Puppet >= 4 only, some sites are still relying on Puppet 3 compatibility.

**Comment by ccnifo** [comment]
OK; Puppet 3 is gone for more than 1 year but that's only a small change, so here it is!

**Comment by kreczko** [comment]
Thanks, this looks good now.
For documentation, we recently started to add special cases (e.g. singularity) to the README.
Feel free to do the same.

Do you want me to merge & you make another PR for documentation or shall I wait?

**Comment by ccnifo** [comment]
OK, I added some entries in the README, thanks.

**Comment by kreczko** [comment]
@ccnifo Thank you very much for the contribution and changes.
Yes, Puppet 3 is gone, maybe my memory is a bit deprecated on this.
I think I will ask tomorrow at the OPS meeting if anyone is still using it. If not, I will replace the Puppet 3 tests with Puppet 5.

**Pull request merged**
